import { colors } from './colors';
import {
  PODCASTS_SECTIONLIST_DATA,
  EXPLORE_PODCASTS_DATA,
  NEW_PODCASTS_DATA,
  HOME_SECTIONLIST_DATA,
  FAVORITES_DATA,
  STATIONS_DATA,
  MUSIC_STATIONS_DATA,
  EXPLORE_SECTIONLIST_DATA,
} from './mockData';

export {
  colors,
  PODCASTS_SECTIONLIST_DATA,
  EXPLORE_PODCASTS_DATA,
  NEW_PODCASTS_DATA,
  HOME_SECTIONLIST_DATA,
  FAVORITES_DATA,
  STATIONS_DATA,
  MUSIC_STATIONS_DATA,
  EXPLORE_SECTIONLIST_DATA,
};
